# syntax=docker/dockerfile:1
FROM golang@sha256:1a6d4452c65dea36aac2e2d606b01b4a029ec90cc1ae53890540ce6173ea77ac AS landrun-build

ARG LANDRUN_COMMIT=811cfff51ceaf3d9843708aa6d22e9b84ccac8b4
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates git \
    && rm -rf /var/lib/apt/lists/*
RUN git init /src \
    && git -C /src remote add origin https://github.com/Zouuup/landrun \
    && git -C /src fetch --depth 1 origin "${LANDRUN_COMMIT}" \
    && git -C /src checkout --detach "${LANDRUN_COMMIT}" \
    && test "$(git -C /src rev-parse HEAD)" = "${LANDRUN_COMMIT}"
RUN cd /src && go build -trimpath -o /landrun ./cmd/landrun

FROM python@sha256:782412e85d0f0984994c290652577d4018aff08145c85b262bb63dc0c7522254

ARG LEAN_TOOLCHAIN=leanprover/lean4:v4.29.0-rc1
ARG COMPARATOR_COMMIT=ae061f79cdf7af458a26348177cfbd62da0123f6
ARG LEAN_DOJO_COMMIT=3bbc4c02fb8a058b282c8d3982a02d6563f3b08a

ENV ELAN_HOME=/opt/elan
ENV PATH=/opt/elan/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
ENV DISABLE_REMOTE_CACHE=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential ca-certificates elan git \
    && rm -rf /var/lib/apt/lists/*
RUN elan toolchain install "${LEAN_TOOLCHAIN}" \
    && elan default "${LEAN_TOOLCHAIN}" \
    && lean --version
RUN git init /opt/vrm/comparator \
    && git -C /opt/vrm/comparator remote add origin https://github.com/leanprover/comparator \
    && git -C /opt/vrm/comparator fetch --depth 1 origin "${COMPARATOR_COMMIT}" \
    && git -C /opt/vrm/comparator checkout --detach "${COMPARATOR_COMMIT}" \
    && test "$(git -C /opt/vrm/comparator rev-parse HEAD)" = "${COMPARATOR_COMMIT}"
COPY comparator-landrun-separator.patch /tmp/comparator-landrun-separator.patch
RUN cd /opt/vrm/comparator \
    && git apply --check /tmp/comparator-landrun-separator.patch \
    && git apply /tmp/comparator-landrun-separator.patch \
    && lake -Kjobs=1 build lean4export comparator \
    && git checkout -- Main.lean \
    && cp /tmp/comparator-landrun-separator.patch .vrm-comparator-landrun-separator.patch \
    && test -z "$(git status --porcelain=v1 --untracked-files=no)"
RUN python -m pip install --no-cache-dir \
    "git+https://github.com/lean-dojo/LeanDojo.git@${LEAN_DOJO_COMMIT}"
COPY --from=landrun-build /landrun /usr/local/bin/landrun
RUN chmod 0555 /usr/local/bin/landrun \
    && chmod -R a-w /opt/vrm/comparator /opt/elan \
    && landrun --version
